name: Build and Release Firmware

on:
  push:
    tags:
      - 'v*.*.*'  # This matches tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker pull espressif/idf:release-v5.2

      - name: Build firmware
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project espressif/idf:release-v5.2 /bin/bash -c "
          . /opt/esp/idf/export.sh &&
          idf.py set-target esp32s3 &&
          idf.py build &&
          cd build &&
          esptool.py --chip ESP32-S3 merge_bin -o firmware.bin @flash_args
          "

      - name: Upload firmware binary
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: build/firmware.bin  # Path to the firmware binary
          artifactContentType: application/octet-stream  # Adjust content type as per your file type

      # - name: Upload firmware binary
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: firmware.bin
      #     path: build/firmware.bin
